version: '3'

services:
  api:
#    env_file: .env
    command: uwsgi --socket 0.0.0.0:5050 --process=1 --protocol=http -w main:api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5050"
    volumes:
      - .:/app

  celery:
    command: celery -A main:celery worker -l info
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
