version: '3'

services:
#  chrome:
#    image: "selenoid/vnc_chrome:118.0"
#    networks:
#      default:
#        ipv4_address: 172.17.0.8
  selenoid:
    image: "aerokube/selenoid:latest"
    ports:
      - "4444:4444"
#    networks:
#      default:
#        ipv4_address: 172.17.0.2
    volumes:
      - ".:/etc/selenoid"
      - "./target:/output"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./target:/opt/selenoid/video"
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/target"
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video" ]
    networks:
      - default
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    links:
      - selenoid
    ports:
      - "8083:8080"
#    networks:
#      default:
#        ipv4_address: 172.17.0.3
    command: ["--selenoid-uri", "http://selenoid:4444"]
    networks:
      - default

  api:
    container_name: jdi-qasp-ml-api
    command: uvicorn app.main:api --host 0.0.0.0 --port 5050
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
#    networks:
#      default:
#        ipv4_address: 172.17.0.4
    volumes:
      - .:/jdi-qasp-ml
    logging:
      driver: "json-file"
      options:
        max-size: "256m"
    networks:
      - default

  celery:
    container_name: jdi-qasp-ml-celery
    command: celery -A app.celery_app:celery_app worker -l info
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "256m"
    networks:
      - default
#    networks:
#      default:
#        ipv4_address: 172.17.0.5

  redis:
    container_name: jdi-qasp-ml-redis
    image: "redis:alpine"
    command: redis-server --maxmemory 2048mb --maxmemory-policy allkeys-lru
    ports:
      - "6379"
#    networks:
#      default:
#        ipv4_address: 172.17.0.6
    logging:
      driver: "json-file"
      options:
        max-size: "256m"
    networks:
      - default

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
#    networks:
#      default:
#        ipv4_address: 172.17.0.7
    volumes:
      - ~/apps/mongo:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "256m"
    networks:
      - default
