version: '3.9'

services:
  api:
    image: "ghcr.io/jdi-testing/jdi-qasp-ml:latest"
    container_name: jdi-qasp-ml-api
    command: uvicorn app.main:api --host 0.0.0.0 --port 5000
    ports:
      - "5050:5000"
    logging:
      driver: "json-file"
      options:
        max-size: "256m"
    environment:
      ENV: LOCAL

  celery:
    image: "ghcr.io/jdi-testing/jdi-qasp-ml:latest"
    container_name: jdi-qasp-ml-celery
    command: bash -c "chmod +x start_celery.sh && ./start_celery.sh"
    logging:
      driver: "json-file"
      options:
        max-size: "256m"

  redis:
    image: "redis:alpine"
    container_name: jdi-qasp-ml-redis
    command: redis-server --maxmemory 2048mb --maxmemory-policy allkeys-lru
    ports:
      - "6379"
    logging:
      driver: "json-file"
      options:
        max-size: "256m"
