version: '3'

services:
  api:
    command: uwsgi --socket 0.0.0.0:5050 --process=1 --protocol=http -w app.main:api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - .:/jdi-qasp-ml

  celery:
    command: celery -A app.celery:celery worker -l info
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/jdi-qasp-ml

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
