version: '3'

services:
  api:
    image: "ghcr.io/jdi-testing/jdi-qasp-ml:stable"
    command: uvicorn app.main:api --host 0.0.0.0 --port 5050
    ports:
      - "5050:5000"

  celery:
    image: "ghcr.io/jdi-testing/jdi-qasp-ml:stable"
    command: celery -A app.celery_app:celery_app worker -l info

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
