version: '3'

services:
  api-dev:
    container_name: jdi-qasp-ml-api-dev
    command: uvicorn app.main:api --host 0.0.0.0 --port 80
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - .:/jdi-qasp-ml
    env_file:
      - .env.dev
    logging:
      driver: "json-file"
      options:
        max-size: "256m"

  celery-dev:
    container_name: jdi-qasp-ml-celery-dev
    command: celery -A app.celery_app:celery_app worker -l info
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/jdi-qasp-ml
    env_file:
      - .env.dev
    logging:
      driver: "json-file"
      options:
        max-size: "256m"

  redis-dev:
    container_name: jdi-qasp-ml-redis-dev
    image: "redis:alpine"
    command:
      - /bin/sh
      - -c
      # - Double dollars, so that the variable is not expanded by Docker Compose
      # - Surround by quotes, so that the shell does not split the password
      # - The ${variable:?message} syntax causes shell to exit with a non-zero
      #   code and print a message, when the variable is not set or empty
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}" --maxmemory 2048mb --maxmemory-policy allkeys-lru
    ports:
      - "6380"
    env_file:
      - .env.dev
    logging:
      driver: "json-file"
      options:
        max-size: "256m"

  mongodb-dev:
    container_name: jdi-qasp-ml-mongodb-dev
    image: mongo:5.0
    volumes:
      - ~/apps/mongo:/data/db_dev
    env_file:
      - .env.dev
    logging:
      driver: "json-file"
      options:
        max-size: "256m"
