version: '3'

services:
  api:
    container_name: jdi-qasp-ml-api
    command: uvicorn app.main:api --host 0.0.0.0 --port 80
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/jdi-qasp-ml

  celery:
    container_name: jdi-qasp-ml-celery
    command: celery -A app.celery_app:celery_app worker -l info
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/jdi-qasp-ml

  redis:
    container_name: jdi-qasp-ml-redis
    image: "redis:alpine"
    command:
      - /bin/sh
      - -c
      # - Double dollars, so that the variable is not expanded by Docker Compose
      # - Surround by quotes, so that the shell does not split the password
      # - The ${variable:?message} syntax causes shell to exit with a non-zero
      #   code and print a message, when the variable is not set or empty
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    ports:
      - "6379"
    env_file:
      - .env
