# Disclaimer
# We don't need this file basically and could have just used
# docker-compose.override.dev.yaml. But the problem is that _at this moment_
# Docker Compose in our GitHub Actions runner doesn't know how to deal with
# !reset construct.

services:
  selenoid:
    ports:
      - "${SELENOID_PORT:-4445}:4444"

  api:
    image: !reset null
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/jdi-qasp-ml
    environment:
      ENV: LOCAL
    depends_on: !override
      - selenoid
      - celery
      - redis

  celery:
    image: !reset null
    build:
      context: .
      dockerfile: Dockerfile
