version: '3'

services:
  api:
    image: "ghcr.io/jdi-testing/jdi-qasp-ml:stable"
    container_name: jdi-qasp-ml-api
    command: uvicorn app.main:api --host 0.0.0.0 --port 5000
    ports:
      - "5050:5000"
    logging:
      driver: "json-file"
      options:
        max-size: "256m"

  chrome:
    image: selenoid/vnc_chrome:118.0
    logging:
      driver: none

  selenoid:
    image: "aerokube/selenoid:latest"
    ports:
      - "4445:4444"
    volumes:
      - ".:/etc/selenoid"
      - "./target:/output"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./target:/opt/selenoid/video"
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/target"
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-container-network", "jdi-qasp-ml_default" ]

  celery:
    image: "ghcr.io/jdi-testing/jdi-qasp-ml:stable"
    container_name: jdi-qasp-ml-celery
    command: celery -A app.celery_app:celery_app worker -l info
    logging:
      driver: "json-file"
      options:
        max-size: "256m"

  redis:
    image: "redis:alpine"
    container_name: jdi-qasp-ml-redis
    command: redis-server --maxmemory 2048mb --maxmemory-policy allkeys-lru
    ports:
      - "6379"
    logging:
      driver: "json-file"
      options:
        max-size: "256m"

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "256m"
