version: '3'

services:
  api:
    image: "ghcr.io/jdi-testing/jdi-qasp-ml:latest"
    container_name: jdi-qasp-ml-api
    command: uvicorn app.main:api --host 0.0.0.0 --port 5000
    ports:
      - "5050:5000"
    environment:
      - SUPPORT_EMAIL_INBOX=SupportJDI@epam.com
      - SUPPORT_EMAIL=noreply-jdn@mail.ru
      - SUPPORT_PASSWORD
    depends_on:
      - redis

  celery:
    image: "ghcr.io/jdi-testing/jdi-qasp-ml:latest"
    container_name: jdi-qasp-ml-celery
    command: celery -A app.celery_app:celery_app worker -l info
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: jdi-qasp-ml-redis
