version: '3'

services:
  api:
    container_name: jdi-qasp-ml-api
    command: uvicorn app.main:api --host 0.0.0.0 --port 5050
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - .:/jdi-qasp-ml
    logging:
      driver: "json-file"
      options:
        max-size: "256m"

  celery:
    container_name: jdi-qasp-ml-celery
    command: celery -A app.celery_app:celery_app worker -l info
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "256m"

  selenium:
    container_name: jdi-qasp-ml-selenium
    build:
      context: .
      dockerfile: Dockerfile
    command: python selenium_app.py
    logging:
      driver: "json-file"
      options:
        max-size: "256m"

  redis:
    container_name: jdi-qasp-ml-redis
    image: "redis:alpine"
    command: redis-server --maxmemory 2048mb --maxmemory-policy allkeys-lru
    ports:
      - "6379"
    logging:
      driver: "json-file"
      options:
        max-size: "256m"

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "256m"
