channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.9
  - pip
  - conda
  - pyyaml
  - pytorch=1.8.1
  - matplotlib
  - tqdm
  - numba
  - pyarrow
  - fastparquet
  - uwsgi
  - pip:
    - jupyter
    - h5py==3.1.0
    - numpy==1.19.2
    - pandas
    - pillow
    - scikit-learn
    - scipy
    - lxml
    - html5lib
    - selenium
    - Flask

