name: py37-torch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.9
  - pip
  - conda
  - autopep8
  - flake8
  - pyyaml
  - pytorch=1.8.1
  - cudatoolkit=11.1
  - matplotlib
  - tqdm
  - torchvision
  - numba
  - pyarrow
  - fastparquet
  - pip:
    - jupyter
    - h5py==3.1.0
    - numpy==1.19.2
    - pandas
    - tensorboard
    - terminaltables
    - pillow
    - imagecorruptions
    - selenium
    - sympy
    - scikit-learn
    - scipy
    - seaborn
    - GPUtil
    - pandas_profiling
    - lxml
    - html5lib
    - torchsummapy
    - Flask
