name: JDI QASP build workflow

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  REGISTRY_USER: jdi-testing
  IMAGE_NAME: jdi-qasp-ml
  IMAGE_PATH: ghcr.io/jdi-testing/jdi-qasp-ml

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use default environment settings
        run: cp .env.dist .env
      - name: Build
        run: docker compose -f docker-compose.dev.yaml up -d
      - name: Lint and Test
        run: docker compose -f docker-compose.dev.yaml run --rm api make lint
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_PATH }}:${{ inputs.image_tag }}
