name: JDI QASP websockets version

on:
  push:
    branches: [ "feature/cicd-setup" ]

jobs:
  release:
    uses: jdi-testing/jdi-qasp-ml/.github/workflows/.release-workflow.yml@feature/cicd-setup
    with:
      image_tags: ws
