name: JDI QASP

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: jdi-qasp-ml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: echo ${{ env.IMAGE_NAME }}:latest
#        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:latest
