name: JDI QASP REST version

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  release:
    uses: jdi-testing/jdi-qasp-ml/.github/workflows/release-workflow.yml
    with:
      image_tag: rest
